create table if not exists public.report_intakes (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients (id) on delete cascade,
  uploaded_by_user_id text,
  file_name text not null,
  file_format text not null,
  report_kind text not null,
  period_label text,
  row_count integer not null default 0,
  summary_payload jsonb not null default '{}'::jsonb,
  status text not null default 'imported',
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.report_intake_rows (
  id bigint generated by default as identity primary key,
  report_intake_id bigint not null references public.report_intakes (id) on delete cascade,
  row_number integer not null,
  row_payload jsonb not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_report_intakes_client_id on public.report_intakes (client_id);
create index if not exists idx_report_intakes_uploaded_by_user_id on public.report_intakes (uploaded_by_user_id);
create index if not exists idx_report_intakes_report_kind on public.report_intakes (report_kind);
create index if not exists idx_report_intake_rows_report_intake_id on public.report_intake_rows (report_intake_id);
