create extension if not exists "pgcrypto";

do $$
begin
  if not exists (select 1 from pg_type where typname = 'user_role') then
    create type public.user_role as enum ('Admin', 'Finance', 'Operations', 'Viewer');
  end if;

  if not exists (select 1 from pg_type where typname = 'interpreter_status') then
    create type public.interpreter_status as enum ('Active', 'Inactive', 'On Hold');
  end if;

  if not exists (select 1 from pg_type where typname = 'payment_frequency') then
    create type public.payment_frequency as enum ('Weekly', 'Biweekly', 'Monthly');
  end if;
end
$$;

create table if not exists public.users (
  id uuid primary key references auth.users (id) on delete cascade,
  email text not null unique,
  full_name text not null,
  role public.user_role not null default 'Viewer',
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  name text not null unique,
  code text unique,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.legal_entities (
  id bigint generated by default as identity primary key,
  name text not null unique,
  country text,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.interpreters (
  id bigint generated by default as identity primary key,
  legal_entity_id bigint references public.legal_entities (id) on delete set null,
  client_id bigint references public.clients (id) on delete set null,
  employee_id text not null unique,
  full_name text not null,
  first_name text,
  last_name text,
  email text not null unique,
  language text not null,
  location text not null,
  country text not null,
  payment_frequency public.payment_frequency not null,
  rate numeric(12, 2) not null,
  status public.interpreter_status not null,
  zoho_contact_id text unique,
  last_synced_at timestamptz,
  sync_status text not null default 'manual',
  sync_error_message text,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.interpreter_client_ids (
  id bigint generated by default as identity primary key,
  interpreter_id bigint not null references public.interpreters (id) on delete cascade,
  client_id bigint not null references public.clients (id) on delete cascade,
  external_id text not null,
  created_at timestamptz not null default timezone('utc', now()),
  constraint uq_interpreter_client_pair unique (interpreter_id, client_id)
);

create table if not exists public.client_mapping_configs (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients (id) on delete cascade,
  source_platform text,
  report_type text,
  field_aliases jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  constraint uq_client_mapping_config unique (client_id, source_platform, report_type)
);

create table if not exists public.routing_rules (
  id bigint generated by default as identity primary key,
  legal_entity_id bigint not null references public.legal_entities (id) on delete cascade,
  client_id bigint not null references public.clients (id) on delete cascade,
  rule_name text not null,
  conditions text,
  destination text,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  constraint uq_routing_rule_name unique (client_id, rule_name)
);

create table if not exists public.uploaded_files (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients (id) on delete cascade,
  uploaded_by_user_id uuid references public.users (id) on delete set null,
  file_name text not null,
  file_format text not null,
  source_platform text not null,
  report_type text not null,
  period text not null,
  storage_path text not null,
  status text not null default 'uploaded',
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.raw_rows (
  id bigint generated by default as identity primary key,
  uploaded_file_id bigint not null references public.uploaded_files (id) on delete cascade,
  row_number integer not null,
  raw_payload jsonb not null,
  parse_status text not null default 'pending',
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.standardized_transactions (
  id bigint generated by default as identity primary key,
  uploaded_file_id bigint not null references public.uploaded_files (id) on delete cascade,
  raw_row_id bigint references public.raw_rows (id) on delete set null,
  row_number integer,
  interpreter_id bigint references public.interpreters (id) on delete set null,
  legal_entity_id bigint references public.legal_entities (id) on delete set null,
  service_date date,
  interpreter_name text,
  external_interpreter_id text,
  minutes numeric(10, 2),
  hours numeric(10, 2),
  rate numeric(12, 4),
  amount numeric(12, 2),
  location text,
  currency text,
  quantity_basis text,
  output_type text,
  processing_status text,
  transaction_code text,
  status text not null default 'pending',
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.validation_errors (
  id bigint generated by default as identity primary key,
  standardized_transaction_id bigint not null references public.standardized_transactions (id) on delete cascade,
  field_name text not null,
  error_code text,
  message text not null,
  is_resolved boolean not null default false,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.exports (
  id bigint generated by default as identity primary key,
  legal_entity_id bigint not null references public.legal_entities (id) on delete cascade,
  exported_by_user_id uuid references public.users (id) on delete set null,
  file_name text not null,
  export_type text not null default 'Invoice',
  storage_path text not null,
  status text not null default 'generated',
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.integration_logs (
  id bigint generated by default as identity primary key,
  integration_name text not null,
  level text not null,
  event_type text not null,
  message text not null,
  detail jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.zoho_crm_settings (
  id bigint generated by default as identity primary key,
  base_url text not null,
  client_id text not null,
  client_secret text not null,
  refresh_token text not null,
  module_name text not null default 'Contacts',
  field_mapping jsonb not null default '{}'::jsonb,
  last_full_sync_at timestamptz,
  last_sync_status text not null default 'not_configured',
  last_sync_error_message text,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_users_role on public.users (role);
create index if not exists idx_clients_code on public.clients (code);
create index if not exists idx_interpreters_legal_entity_id on public.interpreters (legal_entity_id);
create index if not exists idx_interpreters_client_id on public.interpreters (client_id);
create index if not exists idx_interpreters_full_name on public.interpreters (full_name);
create index if not exists idx_interpreters_language on public.interpreters (language);
create index if not exists idx_interpreters_location on public.interpreters (location);
create index if not exists idx_interpreters_country on public.interpreters (country);
create index if not exists idx_interpreters_sync_status on public.interpreters (sync_status);
create index if not exists idx_interpreters_zoho_contact_id on public.interpreters (zoho_contact_id);
create index if not exists idx_interpreter_client_ids_interpreter_id on public.interpreter_client_ids (interpreter_id);
create index if not exists idx_interpreter_client_ids_client_id on public.interpreter_client_ids (client_id);
create index if not exists idx_client_mapping_configs_client_id on public.client_mapping_configs (client_id);
create index if not exists idx_client_mapping_configs_source_platform on public.client_mapping_configs (source_platform);
create index if not exists idx_client_mapping_configs_report_type on public.client_mapping_configs (report_type);
create index if not exists idx_routing_rules_client_id on public.routing_rules (client_id);
create index if not exists idx_routing_rules_legal_entity_id on public.routing_rules (legal_entity_id);
create index if not exists idx_uploaded_files_client_id on public.uploaded_files (client_id);
create index if not exists idx_uploaded_files_uploaded_by_user_id on public.uploaded_files (uploaded_by_user_id);
create index if not exists idx_raw_rows_uploaded_file_id on public.raw_rows (uploaded_file_id);
create index if not exists idx_standardized_transactions_uploaded_file_id on public.standardized_transactions (uploaded_file_id);
create index if not exists idx_standardized_transactions_raw_row_id on public.standardized_transactions (raw_row_id);
create index if not exists idx_standardized_transactions_interpreter_id on public.standardized_transactions (interpreter_id);
create index if not exists idx_standardized_transactions_legal_entity_id on public.standardized_transactions (legal_entity_id);
create index if not exists idx_validation_errors_standardized_transaction_id on public.validation_errors (standardized_transaction_id);
create index if not exists idx_exports_legal_entity_id on public.exports (legal_entity_id);
create index if not exists idx_exports_exported_by_user_id on public.exports (exported_by_user_id);
create index if not exists idx_integration_logs_integration_name on public.integration_logs (integration_name);
create index if not exists idx_integration_logs_level on public.integration_logs (level);
create index if not exists idx_integration_logs_event_type on public.integration_logs (event_type);

create or replace function public.handle_auth_user_created()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users (id, email, full_name, role)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name', coalesce(new.email, 'Unknown User')),
    coalesce((new.raw_app_meta_data ->> 'role')::public.user_role, 'Viewer'::public.user_role)
  )
  on conflict (id) do update
  set
    email = excluded.email,
    full_name = excluded.full_name,
    role = excluded.role;

  return new;
exception
  when invalid_text_representation then
    insert into public.users (id, email, full_name, role)
    values (
      new.id,
      coalesce(new.email, ''),
      coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name', coalesce(new.email, 'Unknown User')),
      'Viewer'::public.user_role
    )
    on conflict (id) do update
    set
      email = excluded.email,
      full_name = excluded.full_name,
      role = excluded.role;

    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert or update on auth.users
  for each row execute procedure public.handle_auth_user_created();
